apiVersion: v1
kind: PersistentVolume
metadata:
  name: node1-pv1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: local-storage
  hostPath:
    path: /local/pv1
 # local:
 #   path: /local/pv1
 # nodeAffinity:
 #   required:
 #     nodeSelectorTerms:
 #     - matchExpressions:
 #       - key: kubernetes.io/hostname
 #         operator: In
 #         values:
 #         - node-1.s000099Q.slurm.io
