apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-c-sa
  namespace: application-c
---
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-c
  namespace: application-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-c
  template:
    metadata:
      labels:
        app: application-c
    spec:
      serviceAccountName: application-c-sa
      containers:
      - name: app
        image: repository.slurm.io/k8s_for_devs/troubleshoot_dev:application-c-v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: HOST
          value: "0.0.0.0"
 
---
apiVersion: v1
kind: Service
metadata:
  name: application-c
  namespace: application-c
spec:
  selector:
    app: application-c
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
