---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-repl-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-200    
  template:
    metadata:
      labels:
        app: app-200 
    spec:
      containers:
      - image: debian:jessie
        command: ["sh", "-c" ,"while true; do echo \"Hello, ${USERNAME}!\"; sleep 2; done"]    
        name: hello
        env:
        - name: USERNAME
          value: user900
...